### ISSUE TITLE
Holbrook Working Code Review - Fantastic Code, Tiny Note

### ISSUE THREAD

**Issue by s-himalia-j** [yingyinlii/team_luther_burbank_proj4#1]
Everything runs properly and looks amazing. The organization is outstanding and the thoroughness of the project is great. 
The only note I have is that there are a lot of prompts in the Nutrient System Analytics [II] section, and I wasn't sure of all the input options. I think the amount of prompting is more personal preference, but if there is more of a list of the selection that you can input for the prompts that would be awesome!

**Comment by yingyinlii** [comment]
Hi,

Thank you for running our code and for your kind note! We are glad to hear that our code worked well for you.

The prompts in Nutrient System Analytics [II] are not necessarily personal preferences. They represent all the data choices that our dataset can provide for you to select from. The prompt was intended as a reminder to maintain consistent formatting to avoid errors.

Once again, thank you and feel free to let us know if you have any other questions!
